apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-router
  namespace: plex
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`plex.attias.io`) || Host(`plex.kiki.home`)
      kind: Rule
      services:
        - name: plex-plex-media-server
          port: 32400