apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-router
  namespace: documents
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keycloak.attias.io`)
      kind: Rule
      services:
        - name: keycloak-http
          port: 80
  tls:
    certResolver: le
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloakadmin-router
  namespace: documents
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kcadmin.attias.io`)
      kind: Rule
      services:
        - name: keycloak-http
          port: 9990
  tls:
    certResolver: le