apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie-router
  namespace: mealie
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`recettes.attias.io`) || Host(`recettes.kiki.home`)
      kind: Rule
      services:
        - name: mealie
          port: 9000