apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie-router
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`recettes.attias.io`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
  tls:
    certResolver: le