apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
    spec:
      containers:
        - env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: BASE_URL
              value: https://recettes.attias.io
            - name: DB_ENGINE
              value: postgres
            - name: PGID
              value: "1000"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: port
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: user
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_FROM_NAME
              value: Kiki Recettes
            - name: SMTP_FROM_EMAIL
              value: recettes@attias.io
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-smtp-secret
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-smtp-secret
                  key: password
            - name: ALLOW_PASSWORD_LOGIN
              value: "false"
            - name: OIDC_AUTH_ENABLED
              value: "true"
            - name: OIDC_PROVIDER_NAME
              value: "authentik"
            - name: OIDC_CONFIGURATION_URL
              value: "https://authentik.attias.io/application/o/mealie/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_SIGNUP_ENABLED
              value: "true"
            - name: OIDC_USER_GROUP
              value: "mealie-users"
            - name: OIDC_ADMIN_GROUP
              value: "mealie-admins"
            - name: OIDC_AUTO_REDIRECT
              value: "true"
            - name: OIDC_REMEMBER_ME
              value: "true"
          name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.10.2
          ports:
            - containerPort: 9000
              protocol: TCP
          # resources:
          #   limits:
          #     memory: "1048576e3"
          volumeMounts:
            - mountPath: /app/data
              name: mealie-data
      restartPolicy: Always
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc