apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-router
  namespace: plex
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.attias.io`)
      kind: Rule
      services:
        - name: plex-plex-media-server
          port: 32400
  tls:
    certResolver: le