apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: plex
  labels:
    app.kubernetes.io/name: tautulli
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      initContainers:
      - name: copy-tools
        image: alpine:latest
        command: [sh, -c]
        args:
          - >-
            cp /tmp/config.ini /config/config.ini
        volumeMounts:
          - mountPath: /config
            name: tautulli-config
          - name: tautulli-config-ini
            mountPath: /tmp/config.ini
            subPath: config.ini
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
          name: tautulli
          image: ghcr.io/tautulli/tautulli:v2.16.1
          ports:
            - containerPort: 8181
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: tautulli-config
      restartPolicy: Always
      volumes:
        - name: tautulli-config
          persistentVolumeClaim:
            claimName: tautulli-config-pvc
        - configMap:
            name: tautulli-config
          name: tautulli-config-ini
