apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli-router
  namespace: plex
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tautulli.attias.io`) && PathPrefix(`/api/`)
      kind: Rule
      priority: 100
      middlewares:
        - name: internal-only
          namespace: traefik
      services:
        - name: tautulli
          port: 8181
    - match: Host(`tautulli.attias.io`)
      kind: Rule
      services:
        - name: tautulli
          port: 8181
      priority: 10
      middlewares:
        - name: authentik
          namespace: traefik
    - kind: Rule
      match: "Host(`tautulli.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
          - kind: Service
            name: ak-outpost-authentik-embedded-outpost
            namespace: authentik
            port: 9000
  tls:
    certResolver: le