apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli-router
  namespace: plex
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tautulli.attias.io`)
      kind: Rule
      services:
        - name: tautulli
          port: 8181
  tls:
    certResolver: le