apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dsm-router
  namespace: dsm
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dsm.kiki.home`)
      kind: Rule
      services:
        - name: dsm-attias-io-service
          port: 5000