apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsm-attias-io-deployment
  namespace: dsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsm.attias.io
  template:
    metadata:
      labels:
        app: dsm.attias.io
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: conf-volume
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: conf-volume
        configMap:
          name: conf-cm
---
apiVersion: v1
kind: Service
metadata:
  name: dsm-attias-io-service
  namespace: dsm
spec:
  selector:
    app: dsm.attias.io
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
