apiVersion: v1
kind: ConfigMap
metadata:
  name: ugreen-conf-cm
  namespace: dsm
data:
  dsm.attias.io.conf: |
    server {   
        listen 9999;
      
      location / {
          proxy_pass http://192.168.1.147:9999/;
        }
    }
