apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: home
  labels:
    app.kubernetes.io/name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant
    spec:
      initContainers:
        - name: install-hacs
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Check if HACS is already installed
              if [ ! -d "/config/custom_components/hacs" ]; then
                echo "HACS not found, installing dependencies..."
                # Add bash to the list of packages
                apk add --no-cache wget unzip bash 
                
                echo "Downloading and running HACS install script..."
                # Download to a temporary file first, then execute with bash
                wget -O /tmp/hacs_install.sh https://get.hacs.xyz
                bash /tmp/hacs_install.sh
              else
                echo "HACS already installed, skipping."
              fi
          volumeMounts:
            - name: homeassistant-config
              mountPath: /config
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
          name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2026.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: homeassistant-config
            - name: ha-config-cm
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: ssh-key-volume
              mountPath: /config/.ssh
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - configMap:
            name: homeassistant-config-cm
          name: ha-config-cm
        - name: ssh-key-volume
          secret:
            secretName: nas-ssh-key
            defaultMode: 0400