apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: memos-router
  namespace: documents
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`memos.attias.io`)
      kind: Rule
      services:
        - name: memos
          port: 5230
    #   priority: 10
    #   middlewares:
    #     - name: authentik
    #       namespace: traefik
    # - kind: Rule
    #   match: "Host(`memos.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)"
    #   priority: 15
    #   services:
    #       - kind: Service
    #         name: ak-outpost-authentik-embedded-outpost
    #         namespace: authentik
    #         port: 9000
  tls:
    certResolver: le