apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-router
  namespace: documents
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.attias.io`)
      kind: Rule
      services:
        - name: paperless-ngx-service
          port: 80