apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: The Grafana dashboard to monitor all services
    gethomepage.dev/group: KikiServer
    gethomepage.dev/icon: grafana.png
    gethomepage.dev/name: Monitoring Dasboard
    gethomepage.dev/widget.type: "grafana"
    gethomepage.dev/widget.url: "https://obs.attias.io"
    gethomepage.dev/pod-selector: ""
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.4.0
    helm:
      releaseName: grafana
      valuesObject:
        admin:
          existingSecret: admin-user-secret
          userKey: admin-user
          passwordKey: admin-password
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Kikiserver
                type: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                isDefault: true
              - name: Kikinode
                type: prometheus
                access: proxy
                url: https://prometheus.node.attias.io
              - name: Kikinas
                type: prometheus
                access: proxy
                url: http://nas.kiki.home:9090/
              # - name: Kikioffsite
              #   type: prometheus
              #   access: proxy
              #   url: http://offsite.kiki.home:9090
              - uid: DS_GARMIN_STATS
                name: GarminInflux
                type: influxdb
                url: "http://influxdb.monitoring.svc.cluster.local:8086"
                database: GarminStats
                user: admin
                secureJsonData:
                  password: $__env{INFLUXDB_PASSWORD}
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards
        dashboardsConfigMaps:
          ceph: "ceph-dashboard"
          node: "node-dashboard"
          k8s: "k8s-dashboard"
          garmin: "garmin-dashboard"