apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.5.7
    helm:
      releaseName: grafana
      valuesObject:
        envFromSecret: admin-user-secret
        grafana.ini:
          server:
            root_url: https://obs.attias.io
          auth:
            signout_redirect_url: "https://authentik.attias.io/application/o/grafana/end-session/"
            oauth_auto_login: true
          auth.generic_oauth:
            name: authentik
            enabled: true
            client_id: $__env{AUTH_CLIENT_ID}
            client_secret: $__env{AUTH_CLIENT_SECRET}
            scopes: "openid profile email"
            auth_url: "https://authentik.attias.io/application/o/authorize/"
            token_url: "https://authentik.attias.io/application/o/token/"
            api_url: "https://authentik.attias.io/application/o/userinfo/"
            # Optionally map user groups to Grafana roles
            # role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
        # admin:
        #   existingSecret: admin-user-secret
        #   userKey: admin-user
        #   passwordKey: admin-password
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Kikiserver
                uid: PC1D92E498B278DEE
                type: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                isDefault: true
              - name: Kikinode
                type: prometheus
                access: proxy
                url: https://prometheus.node.attias.io
              - name: Kikinas
                type: prometheus
                access: proxy
                url: http://nas.kiki.home:9090/
              - uid: DS_GARMIN_STATS
                name: GarminInflux
                type: influxdb
                url: "http://influxdb.monitoring.svc.cluster.local:8086"
                database: GarminStats
                user: admin
                secureJsonData:
                  password: $__env{INFLUXDB_PASSWORD}
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards
        dashboardsConfigMaps:
          smartclt: "smartctl-dashboard"
          ceph: "ceph-dashboard"
          node: "node-dashboard"
          k8s: "k8s-dashboard"
          garmin: "garmin-dashboard"