apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.4.0
    chart: traefik
    helm:
      valuesObject:
        logs:
          general:
            level: "TRACE"
        service:
          type: LoadBalancer
        ports:
          traefik:
            port: 8080
            expose:
              default: true
            exposedPort: 8080
            protocol: TCP
          web:
            port: 8000
            expose:
              default: true
            exposedPort: 80
            targetPort: 8000
            protocol: TCP
            transport:
              respondingTimeouts:
                readTimeout: 600s
                idleTimeout: 600s
                writeTimeout: 600s
          websecure:
            port: 8443
            expose:
              default: true
            exposedPort: 443
            targetPort: 8443
            protocol: TCP
            transport:
              respondingTimeouts:
                readTimeout: 600s
                idleTimeout: 600s
                writeTimeout: 600s
        api:
          dashboard: true
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.kiki.home`)
            entryPoints: ["web"]
        metrics:
          prometheus:
            serviceMonitor:
              enabled: true
        env:
          - name: CLOUDFLARE_EMAIL
            value: christophe.attias@gmail.com
          - name: CF_API_EMAIL
            value: christophe.attias@gmail.com
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token-secret
                key: token
          - name: CLOUDFLARE_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token-secret
                key: token
        podSecurityContext:
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        certificatesResolvers:
          le: # <-- This is the string name you will use in IngressRoutes
            acme:
              email: christophe.attias@gmail.com
              storage: /data/acme.json
              # Use the Staging server for initial testing
              caServer: https://acme-staging-v02.api.letsencrypt.org/directory 
              dnsChallenge:
                provider: cloudflare
                # Use the secret containing your API token (from previous step)
                resolvers: ["1.1.1.1:53", "1.0.0.1:53"] # Use reliable public DNS resolvers
                delayBeforeCheck: 0 # Time to wait before checking for TXT record
        persistence:
          enabled: true
          existingClaim: traefik-data-pvc