apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    directory:
      exclude: '*.json'
      include: '*.yaml'
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.1.4
    helm:
      releaseName: grafana
      valuesObject:
        service:
          type: NodePort
        admin:
          existingSecret: admin-user-secret
          userKey: admin-user
          passwordKey: admin-password
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Kikiserver
                type: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                isDefault: true
              - name: Kikinode
                type: prometheus
                access: proxy
                url: http://192.168.178.34:31530
              - name: Kiki-ds220j
                type: prometheus
                access: proxy
                url: http://192.168.178.29:9090
              - name: Lokiki
                type: loki
                access: proxy
                url: http://loki-gateway.monitoring.svc.cluster.local
              - uid: DS_GARMIN_STATS
                name: GarminInflux
                type: influxdb
                url: "http://influxdb.monitoring.svc.cluster.local:8086"
                database: GarminStats
                user: admin
                secureJsonData:
                  password: $__env{INFLUXDB_PASSWORD}
        dashboards:
          default:
            nodeexporter:
              gnetId: 1860
              revision: 42
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards
        dashboardsConfigMaps:
          default: "grafana-dashboards"
