apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-router
  namespace: rook-ceph
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ceph.attias.io`)
      kind: Rule
      services:
        - name: rook-ceph-mgr-dashboard-external-https
          port: 443
  tls:
    certResolver: le