apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: home
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Kiki's home delivery services
    background: 
        image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
        blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
        saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
        brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
        opacity: 50 # 0-100
    cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
    layout:
    Media:
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Kubernetes Services Dasboards - Server:
        - k0s Dashboard - Server:
            icon: kubernetes-dashboard.png
            href: https://k0s.attias.io/
            description: The k0s admin dashboard on Kikiserver
        - ArgoCD Dashboard - Server:
            icon: argo-cd.png
            href: https://argocd.attias.io/
            description: The ArgoCD dashboard on Kikiserver
        - Monitoring Dashboard - Server:
            icon: grafana.png
            href: https://obs.attias.io/
            description: The Grafana dashboard to monitor all services
        - Prometheus Dashboard - Server:
            icon: prometheus.png
            href: https://prom.attias.io/
            description: The Query and Alerts dashboard to target prometheus
        - Ceph Dashboard - Server:
            icon: ceph.png
            href: https://ceph.attias.io/
            description: The Ceph admin dashboard on Kikiserver
        - Traefik Dashboard - Server:
            icon: traefik.png
            href: https://traefik.attias.io/
            description: The Traefik admin dashboard on Kikiserver
        - Renovate Dasboard - Server:
            icon: renovate.png
            href: https://github.com/cattias/kikiselfhosted/issues
            description: The Renovate Dashboard for the Server on GitHub

    - Kubernetes Services Dasboards - Node:
        - k0s Dashboard - Node:
            icon: kubernetes-dashboard.png
            href: https://k0snode.attias.io/
            description: The k0s admin dashboard on Kikinode
        - ArgoCD Dashboard - Node:
            icon: argo-cd.png
            href: https://argocdnode.attias.io/
            description: The ArgoCD dashboard on Kikinode
        - Traefik Dashboard - Node:
            icon: traefik.png
            href: https://traefiknode.attias.io/
            description: The Traefik admin dashboard on Kikinode
        - Renovate Dasboard - Node:
            icon: renovate.png
            href: https://github.com/cattias/kikinodeapp/issues
            description: The Renovate Dashboard for the Node on GitHub

    - Admin applications:
        - Pihole:
            icon: pi-hole.png
            href: http://pihole.kiki.home/admin/
            description: DNS portal access to Kiki's world
        - Kikivault:
            icon: vaultwarden.png
            href: https://vault.attias.io/
            description: Self-hosted vaultwarden instance on Kikiserver
        - Ugreenkiki:
            icon: ugreen.png
            href: http://nas.kiki.home/
            description: Portal access to Kiki's UGreen NAS
        - CloudFlare Tunnel:
            icon: cloudflare.png
            href: https://one.dash.cloudflare.com/4e24fd66b5017151cc6e26c92c2538ca/networks/tunnels/cfd_tunnel/ba5df757-03b1-4ead-946b-6869d75cd782/edit?tab=publicHostname
            description: The CloudFlare Tunnel management page
        - ASUS Router Admin:
            icon: asus.png
            href: http://192.168.178.64/
            description: ASUS router admin portal
        - Fritzbox Router Admin:
            icon: fritzbox.png
            href: http://192.168.178.1/
            description: Fritzbox router admin portal

    - Arr Stack:
        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.attias.io/
            description: Prowlarr for Kikiflix - Indexer manager
        - Radarr:
            icon: radarr.png
            href: https://radarr.attias.io/
            description: Radarr for Kikiflix - Movie Library manager
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.attias.io/
            description: Sonarr for Kikiflix - TV Show Library manager
        - SABnzbd:
            icon: sabnzbd.png
            href: https://sabnzbd.attias.io/
            description: SABnzbd for Kikiflix - Download manager
        - KikiTube:
            icon: metube.png
            href: https://metube.attias.io/
            description: MeTube app on Kikiserver
        - NZBGeek:
            icon: nzbgeek.png
            href: https://nzbgeek.info/
            description: NZBGeek Search Engine

    - Media Applications:
        - Kikiflix:
            icon: plex.png
            href: https://plex.attias.io/
            description: Kikiflix. What else? Pour le plus grand plaisir de tous.
        - Kikipics:
            icon: immich.png
            href: https://photos.attias.io/
            description: Immich, replacement for Google Photos on Kikiserver.
        - Kikidocs:
            icon: paperless.png
            href: https://paperless.attias.io/
            description: Paperless app on Kikiserver
        - Les recettes de Kiki:
            icon: mealie.png
            href: https://recettes.attias.io/
            description: Les recettes de Kiki
        - Le budget de Kiki:
            icon: actual-budget.png
            href: https://budget.attias.io/
            description: Le budget de Kiki

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
