apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: home
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Kiki's home delivery services
    background: 
        image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
        blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
        saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
        brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
        opacity: 50 # 0-100
    cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
    layout:
    Media:
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Kubernetes Services Dasboards:
        - k0s Dashboard:
            icon: kubernetes-dashboard.png
            href: https://k0s.attias.io/
            description: The k0s admin dashboard on Kikiserver
        - ArgoCD Dashboard:
            icon: argo-cd.png
            href: https://argocd.attias.io/
            description: The ArgoCD dashboard on Kikiserver
        - Monitoring Dashboard:
            icon: grafana.png
            href: https://obs.attias.io/
            description: The Grafana dashboard to monitor all services
        - Ceph Dashboard:
            icon: ceph.png
            href: https://ceph.attias.io/
            description: The Ceph admin dashboard on Kikiserver

    - Media Applications:
        - Kikiflix:
            icon: plex.png
            href: https://plex.attias.io/
            description: THE Kikiflix Plex service. Pour le plus grand plaisir de tous.
        - Kikipics:
            icon: immich.png
            href: https://photos.attias.io/
            description: Immich, replacement for Google Photos on Kikiserver.
        - Kikidocs:
            icon: paperless.png
            href: https://paperless.attias.io/
            description: Paperless app on Kikiserver
        - Les recettes de Kiki:
            icon: mealie.png
            href: https://recettes.attias.io/
            description: Les recettes de Kiki
        - Radarr:
            icon: radarr.png
            href: https://radarr.attias.io/
            description: Radarr for Kikiflix.
        - Transmission:
            icon: transmission.png
            href: https://transmission.attias.io/
            description: Transmission for Kikiflix.
        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.attias.io/
            description: Prowlarr for Kikiflix

    - Admin applications:
        - Kikivault:
            icon: vaultwarden.png
            href: https://vault.attias.io/
            description: Self-hosted vaultwarden instance on Kikiserver
        - SSH:
            icon: terminal.png
            href: https://ssh.attias.io/
            description: Web SSH to Kiki's world
        - Synolokiki:
            icon: synology.png
            href: https://dsm.attias.io/
            description: Portal access to Kiki's Synology NAS

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
