apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: home
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  # bookmarks.yaml: |
  #   - Developer:
  #       - Github:
  #           - abbr: cattias
  #             href: https://github.com/cattias/
  services.yaml: |
    - Kubernetes Services Dasboards:
        - k0s Dashboard:
            href: https://k0s.attias.io/
            description: The k0s admin dashboard on Kikiserver
        - ArgoCD Dashboard:
            href: https://argocd.attias.io/
            description: The ArgoCD dashboard on Kikiserver
        - Monitoring Dashboard:
            href: https://obs.attias.io/
            description: The Grafana dashboard to monitor all services
        - Ceph Dashboard:
            href: https://ceph.attias.io/
            description: The Ceph admin dashboard on Kikiserver

    - Media Applications:
        - Kikiflix:
            href: http://plex.attias.io/
            description: THE Kikiflix Plex service. Pour le plus grand plaisir de tous.
        - Kikipics:
            href: http://photos.attias.io/
            description: Immich, replacement for Google Photos on Kikiserver.
        - Kikidocs:
            href: http://paperless.attias.io/
            description: Paperless app on Kikiserver

    - Other applications:
        - Kikivault:
            href: http://vault.attias.io/
            description: Self-hosted vaultwarden instance on Kikiserver
        - SSH:
            href: http://ssh.attias.io/
            description: Web SSH to Kiki's world
        - Synolokiki:
            href: http://dsm.attias.io/
            description: Portal access to Kiki's Synology NAS

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
