apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspeed
  namespace: home
  labels:
    app.kubernetes.io/name: myspeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myspeed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myspeed
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
          name: myspeed
        - image: germannewsmaker/myspeed
          imagePullPolicy: Always
          ports:
            - containerPort: 5216
              protocol: TCP
          volumeMounts:
            - mountPath: /myspeed/data
              name: myspeed-data
      restartPolicy: Always
      volumes:
        - name: myspeed-data
          persistentVolumeClaim:
            claimName: myspeed-data-pvc
