apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest-router
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`speedtest.attias.io`)
      kind: Rule
      services:
        - name: speedtest
          port: 80
  tls:
    certResolver: le