apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-config-telegram
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    alertmanagerConfig: alertmanager-telegram
spec:
  route:
    groupBy: ['namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: 'telegram'
    routes:
    - receiver: 'null'
      matchers:
        - name: alertname
          matchType: "=~"
          value: "Watchdog"
  receivers:
    - name: 'null'
    - name: 'telegram'
      telegramConfigs:
        - botToken:
            name: telegram-bot-secret
            key: botid
          chatID: 76776913
          parseMode: 'MarkdownV2'
          disableNotifications: false
          sendResolved: true
          message: '{{ template "telegram.message" . }}''