apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-config-slack
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    alertmanagerConfig: alertmanager-slack
spec:
  route:
    groupBy: ['namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: 'slack'
    routes:
    - receiver: 'null'
      matchers:
        - name: alertname
          matchType: "=~"
          value: "Watchdog"
  receivers:
    - name: 'null'
    - name: 'slack'
      slackConfigs:
        - apiURL:
            name: slack-secret
            key: url
          channel: '#kikiserver'
          sendResolved: true
          text: >-
            *[KikiServer]*
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

            *Description:* {{ .Annotations.description }}

            *Details:*
              {{ range .Labels.SortedPairs }} â€¢ *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
