apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-config-slack
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    alertmanagerConfig: alertmanager-slack
spec:
  route:
    groupBy: ['namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: 'slack'
    routes:
    - receiver: 'null'
      matchers:
        - name: alertname
          matchType: "=~"
          value: "Watchdog"
  receivers:
    - name: 'null'
    - name: 'slack'
      slackConfigs:
        - apiURL:
            name: slack-secret
            key: url
          channel: '#kikiserver'
          sendResolved: true
          message: '{{ template "kikiserver.message" . }}'