apiVersion: apps/v1
kind: Deployment
metadata:
  name: garmin-fetch-data
  namespace: monitoring
  annotations:
    argocd-image-updater.argoproj.io/image-list: garmin-fetch-data=thisisarpanghosh/garmin-fetch-data:latest
    argocd-image-updater.argoproj.io/garmin-fetch-data.update-strategy: digest
    argocd-image-updater.argoproj.io/garmin-fetch-data.jsonpath: /spec/template/spec/containers/0/image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garmin-fetch-data
  template:
    metadata:
      labels:
        app: garmin-fetch-data
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: garmin-fetch-data
          image: thisisarpanghosh/garmin-fetch-data:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: fetch-data-config
            - secretRef:
                name: garmin-grafana-secret
          volumeMounts:
            - name: garmin-token
              mountPath: /root/.garminconnect
      volumes:
        - name: garmin-token
          persistentVolumeClaim:
            claimName: garmin-token-pvc