apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nut-exporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-nut-exporter
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 5.4.2
    helm:
      releaseName: prometheus-nut-exporter
      valuesObject:
        metrics:
          enabled: true
      #     serviceMonitor:
      #       enabled: true
      #       targets: [localhost]
      #       labels:
      #         release: kube-prometheus-stack
      #     prometheusRule:
      #       enabled: true
      #       labels:
      #         release: kube-prometheus-stack
