apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nut-exporter
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 9199
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nut-exporter
