apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-exporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: speedtest-exporter
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 5.4.2
    helm:
      releaseName: speedtest-exporter
      valuesObject:
        metrics:
          enabled: true
          prometheusRule:
            enabled: true
            # -- Download speed you want alerts to be triggered in Mbps
            downloadLimit: 500
            # -- Upload speed you want alerts to be triggered in Mbps
            uploadLimit: 70
            # -- Ping latency you want alerts to be triggered in ms
            pingLimit: 10
            # -- Jitter latency you want alerts to be triggered in ms
            jitterLimit: 30
            labels:
              release: kube-prometheus-stack
            rules:
              - alert: SpeedtestSlowInternetDownload
                annotations:
                  description: Internet download speed is averaging {{ "{{ humanize $value }}" }} Mbps.
                  summary: SpeedTest slow internet download.
                expr: |
                  avg_over_time(speedtest_download_bits_per_second{job=~".*{{ include "common.names.fullname" . }}.*"}[2h])
                    < {{ .Values.metrics.prometheusRule.downloadLimit }}
                for: 0m
                labels:
                  severity: critical
