apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian-router
  namespace: documents
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`notes.attias.io`)
      kind: Rule
      services:
        - name: obsidian
          port: 3000
  tls:
    certResolver: le