apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: k0s-router
  namespace: kubernetes-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k0s.attias.io`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-kong-proxy
          port: 443
          serversTransport: dashboard-dns-transport
  tls:
    certResolver: le