apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: k0s-router
  namespace: kubernetes-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`k0s.kiki.home`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-kong-proxy
          port: 443