apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-router
  namespace: photos
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`photos.attias.io`)
      kind: Rule
      services:
        - name: immich-server
          port: 2283