spec:
  ignoreDifferences:
    - group: ""
      kind: Service
      name: offsite-nas-tailnet
      jsonPointers:
        - /spec/externalName
  destination:
    server: https://kubernetes.default.svc
  source:
    registry: https://github.com/cattias