apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-router
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.attias.io`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
      priority: 10
      middlewares:
        - name: authentik
          namespace: traefik
    - kind: Rule
      match: "Host(`bazarr.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
          - kind: Service
            name: authentik-server
            namespace: authentik
            port: 9000
  tls:
    certResolver: le