apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: arr
  labels:
    app.kubernetes.io/name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "10"
            - name: PUID
              value: "1000"
            - name: UMASK
              value: "022"
            - name: TZ
              value: UTC
          name: bazarr
          image: lscr.io/linuxserver/bazarr:v1.5.4-ls331
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767
              protocol: TCP
          volumeMounts:
            - mountPath: /movies
              name: nas-media-volume
              subPath: Movies
            - mountPath: /tv
              name: nas-media-volume
              subPath: "TV Shows"
            - mountPath: /config
              name: bazarr-config
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "timeout 5 stat /movies > /dev/null"
            initialDelaySeconds: 60  # Give it a minute to start up
            periodSeconds: 30       # Check every 30 seconds
            timeoutSeconds: 10      # If the 'stat' command hangs for 10s, fail
            failureThreshold: 3     # Kill the pod after 3 consecutive failures
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ls /movies"
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: nas-media-volume
          persistentVolumeClaim:
            claimName: arr-media-pvc
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc