apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: arr
  labels:
    app.kubernetes.io/name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
          name: bazarr
          image: lscr.io/linuxserver/bazarr:v1.5.3-ls329
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767
              protocol: TCP
          volumeMounts:
            - mountPath: /movies
              name: nas-media-movies-volume
            - mountPath: /tv
              name: nas-media-tv-volume
            - mountPath: /config
              name: bazarr-config
      restartPolicy: Always
      volumes:
        - name: nas-media-movies-volume
          hostPath:
            path: "/mnt/ugreen-media/Movies"
            type: DirectoryOrCreate
        - name: nas-media-tv-volume
          hostPath:
            path: "/mnt/ugreen-media/TV Shows"
            type: DirectoryOrCreate
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc