apiVersion: apps/v1
kind: Deployment
metadata:
  name: beets
  namespace: arr
  labels:
    app.kubernetes.io/name: beets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: beets
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: beets
    spec:
      containers:
        - env:
            - name: PGID
              value: "10"
            - name: PUID
              value: "1000"
            - name: UMASK
              value: "022"
            - name: TZ
              value: UTC
          name: beets
          image: lscr.io/linuxserver/beets:2.5.1-ls305
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8337
              protocol: TCP
          volumeMounts:
            - mountPath: /downloads
              name: nas-media-volume
              subPath: "deemix/inbox"
            - mountPath: /music
              name: nas-media-volume
              subPath: "Music"
            - name: beets-config
              mountPath: /config
            - name: beets-config-yml
              mountPath: /config/config.yaml
              subPath: config.yaml
            - name: beets-custom-init-sh
              mountPath: /custom-cont-init.d/89-install-plugins.sh
              subPath: 89-install-plugins.sh
            - name: beets-custom-init-sh
              mountPath: /custom-cont-init.d/99-run-dropbox.sh
              subPath: 99-run-dropbox.sh
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "timeout 5 stat /music > /dev/null"
            initialDelaySeconds: 60  # Give it a minute to start up
            periodSeconds: 30       # Check every 30 seconds
            timeoutSeconds: 10      # If the 'stat' command hangs for 10s, fail
            failureThreshold: 3     # Kill the pod after 3 consecutive failures
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ls /music"
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: nas-media-volume
          persistentVolumeClaim:
            claimName: arr-media-pvc
        - name: beets-config
          persistentVolumeClaim:
            claimName: beets-config-pvc
        - configMap:
            name: beets-config
          name: beets-config-yml
        - configMap:
            name: beets-custom-init
            defaultMode: 0755
          name: beets-custom-init-sh
