apiVersion: apps/v1
kind: Deployment
metadata:
  name: beets
  namespace: arr
  labels:
    app.kubernetes.io/name: beets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: beets
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: beets
    spec:
      containers:
        - env:
            - name: PGID
              value: "10"
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
          name: beets
          image: lscr.io/linuxserver/beets:latest
          ports:
            - containerPort: 8337
              protocol: TCP
          command: ["watch"]
          args: ["-n 10", "beet import -s /downloads"]

          securityContext:
            runAsUser: 1000
            runAsGroup: 10

          volumeMounts:
            - mountPath: /downloads
              name: nas-media-deemix-volume
            - mountPath: /music
              name: nas-media-music-volume
            - name: beets-config
              mountPath: /config
            - name: beets-config-yml
              mountPath: /config/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: nas-media-deemix-volume
          hostPath:
            path: "/mnt/ugreen-media/deemix/inbox"
            type: DirectoryOrCreate
        - name: nas-media-music-volume
          hostPath:
            path: "/mnt/ugreen-media/Music/beets"
            type: DirectoryOrCreate
        - name: beets-config
          persistentVolumeClaim:
            claimName: beets-config-pvc
        - configMap:
            name: beets-config
          name: beets-config-yml