apiVersion: apps/v1
kind: Deployment
metadata:
  name: deemix
  namespace: arr
  labels:
    app.kubernetes.io/name: deemix
  annotations:
    argocd-image-updater.argoproj.io/image-list: deemix=bambanah/deemix:latest
    argocd-image-updater.argoproj.io/deemix.update-strategy: digest
    argocd-image-updater.argoproj.io/deemix.jsonpath: /spec/template/spec/containers/0/image
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deemix
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deemix
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: UTC
            - name: DEEMIX_SINGLE_USER
              value: "true"
          name: deemix
          image: ghcr.io/bambanah/deemix:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6595
              protocol: TCP
          volumeMounts:
            - mountPath: /downloads
              name: nas-media-deemix-volume
            - mountPath: /config
              name: deemix-config
      restartPolicy: Always
      volumes:
        - name: nas-media-deemix-volume
          hostPath:
            path: "/mnt/ugreen-media/deemix/inbox"
            type: DirectoryOrCreate
        - name: deemix-config
          persistentVolumeClaim:
            claimName: deemix-config-pvc