apiVersion: apps/v1
kind: Deployment
metadata:
  name: deemix
  namespace: arr
  labels:
    app.kubernetes.io/name: deemix
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deemix
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deemix
    spec:
      containers:
        - env:
            - name: PGID
              value: "10"
            - name: PUID
              value: "1000"
            - name: UMASK
              value: "022"
            - name: TZ
              value: UTC
            - name: DEEMIX_SINGLE_USER
              value: "true"
          name: deemix
          image: ghcr.io/bambanah/deemix:v4.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6595
              protocol: TCP
          volumeMounts:
            - mountPath: /downloads
              name: nas-media-volume
              subPath: "deemix/inbox"
            - mountPath: /config
              name: deemix-config
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "timeout 5 stat /downloads > /dev/null"
            initialDelaySeconds: 60  # Give it a minute to start up
            periodSeconds: 30       # Check every 30 seconds
            timeoutSeconds: 10      # If the 'stat' command hangs for 10s, fail
            failureThreshold: 3     # Kill the pod after 3 consecutive failures
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ls /downloads"
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: nas-media-volume
          persistentVolumeClaim:
            claimName: arr-media-smb-pvc
        - name: deemix-config
          persistentVolumeClaim:
            claimName: deemix-config-pvc