apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr-router
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr.attias.io`)
      kind: Rule
      services:
        - name: lidarr
          port: 8686
  tls:
    certResolver: le