apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr-router
  namespace: arr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`lidarr.kiki.home`)
      kind: Rule
      services:
        - name: lidarr
          port: 8686