apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metube-router
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`metube.attias.io`)
      kind: Rule
      services:
        - name: metube
          port: 8081
  tls:
    certResolver: le