apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metube-router
  namespace: arr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`metube.kiki.home`)
      kind: Rule
      services:
        - name: metube
          port: 8081