apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: arr
  labels:
    app.kubernetes.io/name: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overseerr
    spec:
      containers:
        - env:
            - name: PGID
              value: "10"
            - name: PUID
              value: "1000"
            - name: LOG_LEVEL
              value: debug
            - name: PORT
              value: "5055"
            - name: TZ
              value: UTC
          name: overseerr
          image: sctx/overseerr:1.34.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: overseerr-config
      restartPolicy: Always
      volumes:
        - name: overseerr-config
          persistentVolumeClaim:
            claimName: overseerr-config-pvc