apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr-router
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`overseerr.attias.io`)
      kind: Rule
      services:
        - name: overseerr
          port: 5055
  tls:
    certResolver: le