apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: arr
  labels:
    app.kubernetes.io/name: seerr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seerr
    spec:
      containers:
        - env:
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
            - name: UMASK
              value: "022"
            - name: LOG_LEVEL
              value: debug
            - name: PORT
              value: "5055"
            - name: TZ
              value: UTC
          name: seerr
          image: ghcr.io/seerr-team/seerr:v3.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: seerr-config
      restartPolicy: Always
      volumes:
        - name: seerr-config
          persistentVolumeClaim:
            claimName: seerr-config-pvc