# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: seerr-config-pvc
#   namespace: arr
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ceph-block
#   resources:
#     requests:
#       storage: 1Gi