apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: soulsolid-router
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`soulsolid.attias.io`)
      kind: Rule
      services:
        - name: soulsolid
          port: 3535
      priority: 10
      middlewares:
        - name: authentik
          namespace: traefik
    - kind: Rule
      match: "Host(`soulsolid.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
          - kind: Service
            name: ak-outpost-authentik-embedded-outpost
            namespace: authentik
            port: 9000
  tls:
    certResolver: le