# This is a basic workflow to help you get started with Actions

name: Renovate PR Alert Notification

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    if: |
      github.actor == 'renovate[bot]' && 
      startsWith(github.event.pull_request.title, 'Update')
      
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master # (Or discord-action, etc.)
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ðŸš¨ NEW CRITICAL UPDATE PR ðŸš¨
            Repository: ${{ github.repository }}
            Title: ${{ github.event.pull_request.title }}
            URL: ${{ github.event.pull_request.html_url }}
